services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: tic-tac-toe-app
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      #- .:/app
      #- /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npm start"
    networks:
      - app-network
#  backend:
        #      build:
      #        context: ${BACKEND_DIR}
      #      container_name: spring-backend
        #      ports:
      #        - "8080:8080"
        #      networks:
        #        - app-network

  storybook:
    build:
      context: .
      dockerfile: Dockerfile.storybook.dev
    container_name: tic-tac-toe-storybook
    ports:
      - "6006:6006"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./.storybook:/app/.storybook
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: sh -c "npm install && npx storybook dev -p 6006 --ci"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
