services:
  react-app:
    build: .
    container_name: react-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app               # monta tu proyecto local dentro del contenedor
      - /app/node_modules    # evita conflictos entre host y contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true  # asegura que React detecte cambios (útil en Mac/Windows)
      - WATCHPACK_POLLING=true
    command: npm start
